version: '2'

services:

  squid:
    container_name: squid
    build: .
    volumes:
       - www-vol:/var/www/html

    ports:
      - "3128:3128"
      - "3129:3129"
      - "3130:3139"
      - "80:80"

volumes:
  www-vol:

# VOLUMES
# cac-vol:/var/spool/squid3 
# cer-vol:/etc/squid3/ssl_cert 
# log-vo:l/var/log/squid3 
# www-vol:/var/www/html
